[package]
name = "embed-generator"
version = "1.0.0"
authors = ["Aldas <aldas.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.0", features = ["macros", "rt", "rt-multi-thread"] }
warp = "^0.3"
toml = "^0.5"
serde = { version = "^1.0", features = ["derive"] }
serde_with = "^1.4"
serde_json = "^1.0"
serde_urlencoded = "^0.7.0"
ammonia = "^3"